todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls", namespace="web")),
    # path('manager/', include("manager.urls", namespace="manager"))
    
]



if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

web/urls.py
from django.urls import path
from web import views

app_name = "web"

urlpatterns = [
   path("", views.index, name="index"),
   path("login/", views.login, name="login"),
   path("register/", views.register, name="register"),
   path("logout/", views.logout, name="logout"),
   path('edit/<int:id>/', views.edit_todo, name='edit_todo'),
   path('delete/<int:id>/', views.delete_todo, name='delete_todo'),
   path('todo_done/<int:id>/', views.todo_done, name='todo_done'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

web/models.py
from django.db import models
from django.contrib.auth.models import User


class Todo(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_done = models.BooleanField(default=False)
    
    class Meta:
        db_table = "todo"
        verbose_name = "todo"
        verbose_name_plural = "todos"
        ordering = ["-id"]

    def __str__(self):
        return self.name

users/views.py
from django.shortcuts import render

# Create your views here.

web/views.py
from django.shortcuts import render, reverse, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.db.models import Sum
from django.contrib.auth.models import User
from .models import Todo



@login_required(login_url="login/")
def index(request):
    user = request.user
    todos = Todo.objects.filter(is_done=False, user=user)
    dones = Todo.objects.filter(is_done=True, user=user) 
    if request.method == 'POST':
        name = request.POST.get('name')
        Todo.objects.create(name=name, user=user)
        return redirect('web:index')
    else:
        context = {
            'todos': todos,
            'dones':dones
        }
        return render(request, 'web/index.html',  context=context)

def edit_todo(request, id):
    user = request.user
    todos = Todo.objects.filter(is_done=False, user=user)
    dones = Todo.objects.filter(is_done=True, user=user) 
    task = Todo.objects.get(id=id)
    if request.method == 'POST':
        name = request.POST.get('name')
        task.name=name
        task.save()
        return redirect('web:index')
    else:
        context = {
            'task':task,
            'todos': todos,
            'dones':dones
        }
        return render(request, 'web/index.html',  context=context)


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password') 

        user = authenticate(request, username=username, password=password,) 

        if user is not None:
            auth_login(request, user)
            return HttpResponseRedirect(reverse('web:index'))
        else:
            context = {
                'error':True,
                'message':'Invalid email or password'
            }
            return render(request, 'web/login.html', context=context)
    else:
        return render(request, 'web/login.html')
    
def register(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = User.objects.create_user(
            first_name=first_name, 
            last_name=last_name,
            username=username,
            password=password,
        )
        user.save()
        return HttpResponseRedirect(reverse('web:login'))
    
    else:
        return render(request, 'web/register.html')
    
    
def logout(request):
   user = request.user
   auth_logout(request)
  
   return HttpResponseRedirect(reverse('web:index'))


@login_required(login_url='/login')
def delete_todo(request, id):
    todo = Todo.objects.get(id=id)
    todo.delete()
    return redirect('web:index')


@login_required(login_url='/login')
def todo_done(request, id):
    todo = Todo.objects.get(id=id)
    todo.is_done=True
    todo.save()
    
    return redirect('web:index')

templates/base/web_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO</title>
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="index.js"></script>
</head>
<body class="text-[#515151]">

    {%  block container %}
    
    {% endblock %}

</body>
</html>

templates/includes/header.html
{% load static %}

<header class="bg-[#edbb8d] flex justify-between items-center ">
    <h1 class="text-center items-center text-[40px] font-[600] px-3  text-[#7e7c7c]">TO DO</h1>
    <h1 class=" text-center items-center text-[50px] font-[600] text-[#7e7c7c] ">TO DO <span class=" text-[#f3ddc9]">LIST</span></h1>
    <a href="{% url 'web:logout' %}">
    <img class="w-[70px] bg-[#edbb8d]" src="{% static 'images/logout1.webp' %}" alt="logout">
    </a>
</header>

templates/web/add_index.html
{% extends 'base/web_base.html' %}
{% block container %}
{% load static %}


{% endblock %}

templates/web/index.html
{% extends 'base/web_base.html' %}
{% block container %}
{% load static %}
{% include 'includes/header.html' %}

<section class="bg-[#f3ddc9]">
    <section class="wrapper pt-[30px] flex ">
        <div class="flex justify-center w-[33%]">
            <div class="flex items-center ">
                <form  method="post" class="mb-10 md:mb-0">
                    {% csrf_token %}
                    <div class="py-2 px-2 bg-[#fff] rounded-xl flex justify-between">
                        <input type="text" name="name" valu="{{task.name}}" placeholder="Enter Name" class="outline-none px-20 py-3 rounded-2xl bg-[#f0e0c6]">
                        <ul class="flex">
                            <button type="submit" class="mb-1 px-5 py-2 ml-3 mr-11 bg-blue-500 hover:bg-blue-600 text-white font-semibold rounded-md">
                                Add
                            </button>            
                        </ul>
                    </div>
                </form>
            </div>
        </div>
        
        <section class="wrapper  w-[33%]">
            <h1 class="text-[50px] font-[600] text-[#7e7c7c]  text-center">To Do</h1>
            <div class="flex justify-center">
                <div class="">
                    {% for todo in todos %}
                    <div class="flex items-center w-full justify-between">
                        <h1 class="text-[43px] font-[500] text-white mr-3">{{ todo.name }}</h1>
                        <div class="flex">
                            <a href="{% url 'web:edit_todo' id=todo.id %}">
                                <button type="button" class="mb-1 px-5 py-2 mr-4 bg-blue-500 hover:bg-blue-600 text-white font-semibold rounded-md">
                                    Edit
                                </button>
                            </a>
                            <a href="{% url 'web:delete_todo' id=todo.id %}">
                                <button type="button" class="mb-1 px-4 py-2 mr-4 bg-red-500 hover:bg-red-600 text-white font-semibold rounded-md">
                                    Delete
                                </button>
                            </a>
                            <a href="{% url 'web:todo_done' id=todo.id %}">
                                <button type="button" class="mb-1 px-4 py-2 bg-green-500 hover:bg-green-600 text-white font-semibold rounded-md">
                                    Done 
                                </button>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        <section class="w-[33%] ">
            <h1 class=" text-center items-center text-[50px] font-[600] text-[#7e7c7c] ">TO DO <span class=" text-[#edbb8d]">LIST</span></h1>
            <div class="">
                {% for todo in dones %}
                <div class="text-center">
                    <p class="text-[43px] font-[500] text-[#000] mr-3">{{ todo.name }}</p>
                </div>
                {% endfor %}
            </div>
        </section>
    </section>
</section>

{% endblock %}

templates/web/login.html
{% extends 'base/web_base.html' %}
{% block container %}
{% load static %}

<section class=" grid grid-cols-1 md:grid-cols-2 h-screen">
    <div class="col-span-1 hidden md:flex">
        <img src="{% static 'images/login.png' %}" alt="image" class="w-full">
    </div>
    <div class="col-span-1 h-screen flex justify-center items-center">
        <div class="text-center">
            <h1 class="text-[32px] font-semibold mb-5">LOGIN NOW</h1>
            <p class="w-[90%] md:w-[70%] m-auto mb-5">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vel soluta, quidem reiciendis necessitatibus unde culpa?</p>
            <form action="" id="login-form" method="post" class="w-[90%] md:w-[70%] m-auto">
                {% csrf_token %}   
                <div class="flex items-center justify-between border border-gray-300 mb-4 rounded-2xl">
                    <input 
                        type="text" 
                        name="username" 
                        id="username" 
                        placeholder="Enter Your username" 
                        class="flex-grow w-full px-4 py-3 rounded-2xl outline-none"
                    >
                    <span id="username-feedback" class="mx-2 text-2xl flex items-center space-x-5 ">
                    </span>
                </div>
                
                <input type="password" name="password" placeholder="Enter Your Password" class="w-full outline-none border rounded-2xl py-3 px-5 mb-5">
                <button type="submit" class="fadeOutLeftBig py-3 px-5 bg-red-500 text-white text-[14px] font-semibold rounded-xl">LOGIN</button>
            </form>
            <p class="text-[14px] mt-5">Don't have an Account? <a href="{% url 'web:register' %}" class="text-[14px] text-red-500">Sign Up</a></p>
        </div>
    </div>
</section>

{% endblock %}

templates/web/register.html
{% extends 'base/web_base.html' %}

{% load static %}

{% block container %}


    <section class="grid grid-cols-1 md:grid-cols-2 h-screen">
        <div class=" col-span-1 hidden md:flex">
            <img src="{% static 'images/register1.png' %}" alt="image" class="w-full">
        </div>
        <div class=" col-span-1 h-screen flex justify-center items-center">
            <div class="text-center">
                <h1 class="text-[32px] font-semibold mb-5">SIGN UP NOW</h1>
                <p class="w-[90%] md:w-[70%] m-auto mb-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam omnis sint cum rem laborum in. </p>
                <form action="" method="post" class="w-[90%] md:w-[70%] m-auto">
                    {% csrf_token %}
                    <input type="text" name="username" placeholder="Enter username" class=" w-full outline-none boredr rounded-2xl py-3 px-5 mb-5">
                    <input type="text" name="first_name" placeholder="Enter first name" class=" w-full outline-none boredr rounded-2xl py-3 px-5 mb-5">
                    <input type="text" name="last_name" placeholder="Enter last name" class=" w-full outline-none boredr rounded-2xl py-3 px-5 mb-5">
                    <input type="password" name="password" placeholder="Enter your password" class=" w-full outline-none boredr rounded-2xl py-3 px-5">
                    <button type="submit" class="py-3 px-5 bg-red-500 text-white text-[14px] font-semibold rounded-xl">Sign Up</button>
                </form>
                {% if error %}
                    <p class="mt-5 text-[14px] text-[red]">{{message}}</p>
                {% endif %}
                <p class="text-[14px] mt-5">already have an Account <a href="{% url 'web:login' %}" class=" text-red-500">Login</a></p>
            </div>
        </div>
    </section>

{% endblock %}